version: '3'
services:
  db:
    image: postgres
    hostname: db
    environment:
      GET_HOSTS_FROM: dns
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: mysecretpassword
    ports:
    - 5432:5432
    networks:
      - pgnetwork
    container_name: shopifystoredb
  app:
    image: kisulken/shopifystoreapi:v5
    build: .
    environment:
      GET_HOSTS_FROM: dns
    volumes:
    - .:/go/src/shopfiyStoreAPI
    ports:
    - 8080:8080
    depends_on:
    - db
    links:
    - db
    networks:
    - pgnetwork
    container_name: shopifystoreapi
    labels:
      kompose.service.type: LoadBalancer
networks:
  pgnetwork:
    driver: "bridge"